trigger:
- master

pool:
  vmImage: windows-latest

steps:
- task: Application security testing@2020
  inputs:
    projectName: 'ADO-Plugin-Freeport-SAST-1'
    enableProxy: false
    enableSastScan: true
    CheckmarxService: 'Cx Private Cloud 9.3'
    fullTeamName: 'CxServer\SP\America\NA-RR-PS\RDR3\ADO_CXFLOW_DOCKER'
    incScan: false
    forceScan: true
    comment: 'SAST scan initiated via ADo plugin'
    enableDependencyScan: false